# Generated by Django 5.0.6 on 2024-06-29 05:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to=api.models.upload_to),
        ),
    ]
