# Generated by Django 5.0.6 on 2024-07-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
